#!/bin/bash
notify-send "Notmuch: tagging..."

notmuch tag -new +ec -- tag:new from:aptivate@econsensus.org
notmuch tag -new +ec -- tag:new from:aptivateprivate@econsensus.org
notmuch tag -new +bj -- tag:new from:mark@bitterjug.com
notmuch tag -new +bj -- tag:new from:bitterjug@gmail.com

notmuch tag -new +youwin -- to:dfidyouwin-team@aptivate.org
notmuch tag -new +youwin -- from:r-ough@dfid.gov.uk
notmuch tag -new +youwin -- to:r-ough@dfid.gov.uk

# redmine stuff
notmuch tag +redmine +projects -- from:projects@aptivate.org

#==============================================
# Any remaining 'new' mail goes into the inbox
notmuch tag +unread +inbox -new -- tag:new


